apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-policy-ctrl
spec:
  replicas: 1
  selector:
    matchLabels:
      name: config-policy-ctrl
  template:
    metadata:
      labels:
        name: config-policy-ctrl
    spec:
      serviceAccountName: config-policy-ctrl
      imagePullSecrets:
        - name: multiclusterhub-operator-pull-secret
      containers:
        - image: quay.io/open-cluster-management/config-policy-controller:1.0.0-PR6-9a3f233e38063dd08f72f39fbd289f83afbc35de
          name: config-policy-ctrl
          command:
          - config-policy-controller
          - --watch-ns=config-policy-test
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: config-policy-test
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "config-policy-ctrl"