name: Run KinD tests

on:
  push:
    branches: [ main, release-2.3 ]
  pull_request:
    branches: [ main, release-2.3 ]

defaults:
  run:
    shell: bash
    working-directory: config-policy-controller

jobs:
  main:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        go: [ '1.14' ]
    name: Test on Go ${{ matrix.go }}
    steps:
    - name: Checkout Config Policy Controller
      uses: actions/checkout@v2
      with:
        path: config-policy-controller
        fetch-depth: 0 # Fetch all history for all tags and branches

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v2
      id: go
      with:
        go-version: ${{ matrix.go }}

    - name: Verify modules
      run: go mod verify

    - name: Verify format
      run: |
        make fmt
        git diff --exit-code

    - name: Create K8s KinD Cluster
      run: make kind-bootstrap-cluster

    - name: Build and Push Test Container Image to KIND node
      run: |
        make build-images

    - name: Unit and Integration Tests
      run: make test

    - name: E2E Tests
      run: make e2e-test

    - name: Clean up
      run: make kind-delete-cluster

