name: KinD tests

on:
  push:
    branches: [ main, release-2.3 ]
  pull_request:
    branches: [ main, release-2.3 ]

defaults:
  run:
    shell: bash
    working-directory: config-policy-controller

jobs:
  main:
    runs-on: ubuntu-18.04
    env:
      REGISTRY: localhost:5000
      WATCH_NAMESPACE: managed
    strategy:
      matrix:
        go: [ '1.14' ]
    name: KinD tests
    steps:
    - name: Checkout Config Policy Controller
      uses: actions/checkout@v2
      with:
        path: config-policy-controller
        fetch-depth: 0 # Fetch all history for all tags and branches

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v2
      id: go
      with:
        go-version: ${{ matrix.go }}

    - name: Verify modules
      run: go mod verify

    - name: Verify format
      run: |
        make fmt
        git diff --exit-code

    - name: Unit and Integration Tests
      run: |
        curl -L https://go.kubebuilder.io/dl/2.3.0/"$(go env GOOS)"/"$(go env GOARCH)" | tar -xz -C /tmp/
        sudo mv /tmp/kubebuilder_2.3.0_"$(go env GOOS)"_"$(go env GOARCH)" /usr/local/kubebuilder
        export PATH=$PATH:/usr/local/kubebuilder/bin
        make test

    # - name: Create K8s KinD Cluster
    #   run: make kind-bootstrap-cluster-dev

    # - name: Build and Push Test Container Image to KinD node
    #   run: |
    #     make build-images
    #     make kind-deploy-controller-dev

    - name: E2E Tests
      run: |
        export GOPATH=$(go env GOPATH)
        go get github.com/onsi/ginkgo/ginkgo
        go get github.com/onsi/gomega/...
        make kind-bootstrap-cluster-dev
        make build-instrumented
        make run-instrumented
        make e2e-test
        make stop-instrumented

    - name: Coverage Report
      run: |
        export GOPATH=$(go env GOPATH)
        go get github.com/wadey/gocovmerge
        ${GOPATH}/bin/gocovmerge $(PWD)/coverage_* >> coverage.out
        cat coverage.out
    
    - name: Debug
      if: ${{ failure() }}
      run: |
        kubectl describe pods -n ${WATCH_NAMESPACE}
        kubectl describe configurationpolicies.policy.open-cluster-management.io -n ${WATCH_NAMESPACE}
    
    - name: Clean up cluster
      if: ${{ always() }}
      run: make kind-delete-cluster

